# component deletion
synapse_admin_component_delete:
    path: /{zoneId}/{componentId}/delete
    defaults:
        _controller: "SynapseAdminBundle:ZoneAdmin:delete"
    methods:
        - GET
    requirements:
        id: \d+
