# Templates
synapse_admin_template:
    resource: "routing/template.yml"
    prefix: /templates

# Zones
synapse_admin_zone:
    resource: "routing/zone.yml"
    prefix: /zones

# Medias
synapse_admin_media:
    resource: "routing/media.yml"
    prefix: /medias

synapse_admin_image:
    resource: "routing/image.yml"
    prefix: /medias/images
